### PR TITLE
[WIP] add a console demo

### PR DESCRIPTION
**Pull request by mishfit**
Add a console which:

- [x] takes in file name
- [ ] takes in console input
- [x] writes QR code to specified file ( in png format)
- [ ] writes stream to console output

### CODE REVIEW

**Comment by codebude** [comment]
Hi @mishfit ,

Thanks for your support. I merged your changes. Is there a reason why you didn't added a parameter for file formats and console ouput? Otherwise I'll implement it during the next days.

Best regards,
Raffael

**Comment by mishfit** [comment]
Oh, hey, I'm glad you liked it.

I labeled the PR '[WIP]' as in "work in progress" (I kind of took some cues from this [article](http://blog.half-ogre.com/posts/software/rules-of-the-open-road/) (see number 4).

I also, added some tasks to the PR (I haven't finished two of them).

I was hoping to get some criticism/review so I created the PR before everything was ready (I probably should have created an issue first).

**Comment by codebude** [comment]
D'Oh! I didn't see the WIP...sorry!

Nevertheless, if you sync with the master branch, you'll see that I already have implemented multiple filetype support.

**Comment by mishfit** [comment]
Cool, I'll take a look at it.

Also, I took a dependency on the [NDesk.Options](https://www.nuget.org/packages/NDesk.Options/) package. I didn't know if you'd like that. It is entirely possible to pull the specific `OptionSet` code in if you'd prefer to limit the nuget package dependencies.

**Comment by codebude** [comment]
As long as those dependencies are only inside the demo apps and not inside the main library, it's no problem for me. Writing a new demo, because one of the dependencies drops support is not that problematic, than seeing the main library crashing, because someone dropped his lib.

**Pull request merged**
