### PR TITLE
Ensure that an OTP's issuer and label values are escaped correctly

### PR DESCRIPTION
**Pull request by josh-**
## Summary

This PR fixes/implements the following **bugs/features**:

* [x] Creating an OTP with an issuer/label that contains a space or other restricted characters does not properly escape the issuer/label

### What existing problem does the pull request solve?**

Currently, if you create an OTP with an issuer that contains a space, for example:

```cs
var oneTimePassword = new OneTimePassword {
	Issuer = "Google Google",
	Label = "test@google.com",
	Secret = "pwq6 5q55"
};
```

and then call `ToString` on that `oneTimePassword`, that will return:

`otpauth://totp/Google Google:test@google.com?secret=pwq65q55&issuer=Google%20Google`

(note the first "Google Google" is not escaped, like the second one in the `issuer` parameter)

which then looks like this in Google Authenticator after scanning the resulting QR code:

File

This PR resolves this issue by correctly escaping both instances of the issuer in the URL, which then appears correctly in Google Authenticator:

`otpauth://totp/Google%20Google:test@google.com?secret=pwq65q55&issuer=Google%20Google`

## Test plan

Test cases have been added.

## Closing issues

N/A

### CODE REVIEW

**Comment by prvacy** [comment]
I discovered the same problem yesterday, thank you for the fix!

**Comment by tom-156842** [comment]
Thanks for this fix, it addresses issue #375.

I suggest also escaping the `Label` value, since an [email address](https://en.wikipedia.org/wiki/Email_address#Local-part) can contain `/` and `?` characters.

**Comment by josh-** [comment]
> Thanks for this fix, it addresses issue #375.
> 
> I suggest also escaping the `Label` value, since an [email address](https://en.wikipedia.org/wiki/Email_address#Local-part) can contain `/` and `?` characters.

Thanks @tom-156842, done 👍

**Comment by hdocsek** [comment]
@codebude Do you any update on when this fix will be released?

**Review by doggy8088 — APPROVED** [review]
LGTM

@codebude

**Comment by Shane32** [comment]
All changes here look good.  Generated QR codes scan properly with Google Authenticator.  Tests have already been added :+1:

**Pull request merged**
