### PR TITLE
blazor demo + shared UI code

### PR DESCRIPTION
**Pull request by mabroukmahdhi**
## Summary
I tried to make a Demo for blazor :)

This PR fixes/implements the following **feature**:

* [x] Feature : Shared code for QRCode view (Windows) can be used for any windows platform (Xamarin, MAUI, Blazor, WinForms....)  
 
2022-02-21 21_38_20-QRCoderDemo Blazor

### CODE REVIEW

**Comment by mabroukmahdhi** [comment]
I think the shared UI Code should be set in a separate class library. Because it's only for Demo. What do you think?

**Comment by codebude** [comment]
Hi @mabroukmahdhi, Thanks for the PR and the effort you certainly put in. I hope you are not too upset if I reject the PR, but I think the demo is too extensive and in-depth. 

QRCoder is a class library for generating QR codes. The demo projects in this repository are only intended to show in a **simple** and **compact** way how the library could be used as an example. The Blazor demo is visually very successful, but far from simple in terms of code size. Maybe one can't write a Blazor demo shorter - I don't know enough about Blazor - but the demo is just too big for a simple example. 

In addition, the PR inserts code that is only relevant for the demo into the core library (QRCoder/UI/*-files). However, I would like to keep these free of any demo code.

I hope you can understand my decision. Nevertheless, thanks again for your effort!

**Comment by codeputer** [comment]
It may be too complex, but I'm very interested in anything Blazor! 🙂

R
________________________________

**Comment by codebude** [comment]
@codeputer feel free to fork/clone @mabroukmahdhi's branch (https://github.com/mabroukmahdhi/QRCoder/tree/add-blazor-demo) and fiddle around with the demo. As long as @mabroukmahdhi doesn't delete his repo, the sample code won't be gone and can be a source of inspiration for everyone interested in a Blazor demo.
But as I said - for this project repository it's just too huge in my opinion and also breaking the philosphy of QRCoder (by adding demo code to the core library.)

**Pull request closed without merging**
