### PR TITLE
Barcodes you can use backgrounds with.

### LINKED ISSUE #294: Transparent barcodes
I've been hacking a new renderer for your library to make it possible to have see though barcodes. 

image

I wrote a version of the QRCode class to do this. If you are keen I'll raise a pull request, and you guys can make it production ready. 
Let me know if you are keen.

### PR DESCRIPTION
**Pull request by NigelThorne**
**Summary**

Generate barcodes that can have background images and custom retackle images in the corners. 

**Test plan**

image
Try it out. :)

**Closing issues**
closes  #294

### CODE REVIEW

**Comment by NigelThorne** [comment]
ok .. this may be good enough.. tell me what you think .

**Comment by NigelThorne** [comment]
We could put back support for the 'overlay image' aswell. I took it out for now. 
Also.. we could use the light color as a wash to put over the image... so people can control how much the image gets faded by to allow the black dots to get more contrast.

**Comment by codebude** [comment]
Hi @NigelThorne thanks for your work and the pull request. I'll review within the next days. One thing I already have in mind: Would you mind, if I rename it from "LogoQRCode" to "ArtQRCode"? Background: I think "Logo" may a bit misleading, because users can already place logos on other QRCode rendering classes. Art (or Artistic) would better describe the type of rendering in my  opinion.

**Comment by NigelThorne** [comment]
sounds good. 
I'd like to re-add the logo behaviour on top of the art qr code.

**Comment by NigelThorne** [comment]
I've fixed the behaviour so the pixels get cropped to the module square size. This has the side effect that if you set the pixel size large enough you get a standard barcode.

**Comment by AlexandreZaytsev** [comment]
Hi! I'm a beginner in C#, want to try your ArtQRCode.cs please tell me how to use it correctly in a demo project (QRCoder/QRCoderDemo/RenderQrCode())(https://github.com/codebude/QRCoder)?

```
       private void RenderQrCode()
        {
            string level = comboBoxECC.SelectedItem.ToString();
            QRCodeGenerator.ECCLevel eccLevel = (QRCodeGenerator.ECCLevel)(level == "L" ? 0 : level == "M" ? 1 : level == "Q" ? 2 : 3);
            using (QRCodeGenerator qrGenerator = new QRCodeGenerator())
            using (QRCodeData qrCodeData = qrGenerator.CreateQrCode(textBoxQRCode.Text, eccLevel))

//            using (QRCode qrCode = new QRCode(qrCodeData))
            using (ArtQRCode qrCode = new ArtQRCode(qrCodeData))
            {

                pictureBoxQRCode.BackgroundImage = qrCode.GetGraphic(20);// (20, GetPrimaryColor(), GetBackgroundColor(), GetIconBitmap(), (int)iconSize.Value);

                this.pictureBoxQRCode.Size = new System.Drawing.Size(pictureBoxQRCode.Width, pictureBoxQRCode.Height);
                //Set the SizeMode to center the image.
                this.pictureBoxQRCode.SizeMode = PictureBoxSizeMode.CenterImage;

                pictureBoxQRCode.SizeMode = PictureBoxSizeMode.StretchImage;
            }
```
?
but the image is created by squares not dots
tell me - how to do it correctly? 
thank you

**Comment by AlexandreZaytsev** [comment]
stop! everything is ok ))
but large squares without tails like you have in the picture ))

**Comment by NigelThorne** [comment]
@AlexandreZaytsev  You can pass custom images to use as the corners. They have to be something that would scan though.. :)  so they need to have the same 'ring' type structure with the right thickness of black and white. Google use this 
image

**Comment by NigelThorne** [comment]
@codebude Any plans to merge this :)

**Comment by NigelThorne** [comment]
@AlexandreZaytsev If you make the background transparent you can put the background in with a paint package. This lets you cheat and remove dots where faces are etc and still get something that scans (due to the error correcting nature of qr)

**Review by GirishSolanki — APPROVED** [review]

**Pull request merged**
