### PR TITLE
Adding ASCII QR Codes as a format. 

### PR DESCRIPTION
**Pull request by navidmatin**
Added a way to print ASCII representation of the QR codes. Here is an example of output:

>                                                                                        
>             █████████████████████   ███   ██████      █████████████████████            
>             ███               ███   ███               ███               ███            
>             ███   █████████   ███   ██████   ██████   ███   █████████   ███            
>             ███   █████████   ███      ██████   ███   ███   █████████   ███            
>             ███   █████████   ███   ████████████      ███   █████████   ███            
>             ███               ███   ██████            ███               ███            
>             █████████████████████   ███   ███   ███   █████████████████████            
>                                     ███         ███                                    
>                   ███         █████████      ███   ████████████   █████████            
>             ████████████         ██████   ███         ██████      ██████               
>                ███      ███   ███   ██████      ██████      █████████   ███            
>             ████████████         ██████            ████████████                        
>             ███   ███   ████████████      ███   ███      ███      ███   ███            
>                                     ███            ████████████                        
>             █████████████████████   ██████   ██████   ███   ██████   ██████            
>             ███               ███                  ███████████████   ███               
>             ███   █████████   ███         ███   ███      ███      ███   ███            
>             ███   █████████   ███         ██████   ████████████   ██████               
>             ███   █████████   ███   ███                     ███   ███   ███            
>             ███               ███               ██████   ███   ███                     
>             █████████████████████      ███   ██████      ██████   ███   ███            
>

### CODE REVIEW

**Comment by codebude** [comment]
Hi @navidmatin ,

thanks for your PR. One question before merging: With which scanner do you scan those codes? I tried to scan it with [ZXing Barcode Scanner](https://play.google.com/store/apps/details?id=com.google.zxing.client.android&hl=de) for Android, which is really popular, but it doesn't work? Is that because Giothub adds whitespaces around the chars?

**Comment by navidmatin** [comment]
Yeah Github spacing breaks the QR code. If you copy paste it to notepad it will work. I used [Lightning QR](https://play.google.com/store/apps/details?id=com.application_4u.qrcode.barcode.scanner.reader.flashlight&hl=en) to test the QR codes. 
The general problem with ASCII QR codes is that it doesn't guarantee readable QR codes since it depends on how the characters get printed/shown on the page.

**Comment by codebude** [comment]
It seems to work. I'll merge it and do some changes in naming. ASCIIQrCode to AsciiQrCode, ..., because of naming standardization.

**Comment by codebude** [comment]
Hi @navidmatin ,

I merged the code and did some minimal refactoring. (Naming and code/parameter comments.) You can see the changes over here: https://github.com/codebude/QRCoder/commit/d78808c195be3b34b38f90fc8e6f8d62330fbb87

Also I added your encoder to the readme.md on the main page... 
https://github.com/codebude/QRCoder#special-rendering-types

...and wrote some info for the wiki:
https://github.com/codebude/QRCoder/wiki/Advanced-usage---QR-Code-renderers#22-asciiqrcode-renderer-in-detail

If you want to add or correct something - let me know!

**Pull request merged**
