### PR TITLE
Support for Xaml

### PR DESCRIPTION
**Pull request by rozmansi**
This PR adds support for XAML to make QRCoder directly usable in WPF projects.

Furthermore, it extends QRCoderConsole utility with the ability to output XAML files.

The code has been ported from https://github.com/Amebis/eduVPN/blob/master/eduVPN.Client/QRCoder/XamlQRCode.cs under originating author permission.

Example use-case:
```C#
public class TOTPQRConverter : IMultiValueConverter
{
    public object Convert(object[] values, Type targetType, object parameter, CultureInfo culture)
    {
        try
        {
            var secret = values[0] as string;
            var hostname = values[1] as string;
            var displayname = values[2] as string;
            var otp_uri = string.Format("otpauth://totp/{1}?secret={0}&issuer={2}",
                secret,
                hostname,
                HttpUtility.UrlEncode(displayname));

            var qr_generator = new QRCodeGenerator();
            var qr_code_data = qr_generator.CreateQrCode(otp_uri, QRCodeGenerator.ECCLevel.Q);
            var qr_code = new XamlQRCode(qr_code_data);
            return qr_code.GetGraphic(1, false);
        }
        catch { }

        // Fallback to blank image.
        return new Uri("pack://application:,,,/Resources/Blank.png");
    }

    public object[] ConvertBack(object value, Type[] targetTypes, object parameter, CultureInfo culture)
    {
        throw new NotImplementedException();
    }
}
```

### CODE REVIEW

**Comment by codebude** [comment]
Hi @rozmansi ,

at first - please excuse the long reaction time - my free time seemed to be virtually zero the last months. Many thanks for your PR and your work. I'm happy to include your code into QRCoder.

**Comment by codebude** [comment]
One more question, @rozmansi - would you mind writing a part for your QRCode type for this wiki page? https://github.com/codebude/QRCoder/wiki/Advanced-usage---QR-Code-renderers#24-bitmapbyteqrcode-renderer-in-detail

**Comment by rozmansi** [comment]
I have put it on my TODO list. However, my reaction time is as bad as yours = programmer's professional flaw.

**Comment by rozmansi** [comment]
Here you go... Description added to https://github.com/codebude/QRCoder/wiki/Advanced-usage---QR-Code-renderers

**Comment by codebude** [comment]
Hi Simon,

many thanks for updating the Wiki :+1:

**Comment by codebude** [comment]
Hi @rozmansi , 30 minutes ago I released [version 1.3.3 on Nuget](https://www.nuget.org/packages/QRCoder/). So your renderer is available in the official Nuget package from now on.

**Pull request merged**
