### PR TITLE
BML is not BMP

### PR DESCRIPTION
**Pull request by Hydroque**
This is to promote correctness.

### CODE REVIEW

**Comment by codebude** [comment]
Could you please explain your change? You changed the third bit of the bitmap file header from 0x4C to 0x50. This byte is the first part of the "size"-block in bitmap file header. So how does the belong to your title: "bml is not bmp"?

**Comment by Hydroque** [comment]
Nevermind c:

**Comment by codebude** [comment]
So this Pull request is obsolete?

**Comment by Hydroque** [comment]
Yep. My bad.

**Pull request closed without merging**
