### PR TITLE
add an easy-to-call one-hit wrappers to generate PNG and BMP image byte array

### PR DESCRIPTION
**Pull request by sbrickey**
* Feature : single static methods - no instances, no disposables, just call and go.

### CODE REVIEW

**Comment by AdamWillden** [comment]
Oh, although I would appreciate if there were overloads for passing in a payload rather than just the plaintext

**Comment by codebude** [comment]
Hi @sbrickey ,

I understand your idea/concept, but I don't like to merge it now for sake of completeness. I think if we add this feature to the QRCoder it should be consistent over all QR renderer classes and not only for some (like it is now). I fear that users could get confused if only some renderer support this "shortcuts". 

Would you mind added this shortcuts for the other rendering classes, too? If so, I would be happy to merge it.

**Comment by Ruffio** [comment]
@sbrickey would you like to implement the suggestions by @codebude 
I don't think this PR will be merged without these additions ;-)

**Comment by codebude** [comment]
Finally merged. Thanks for your support. Feel free to add some parts on the https://github.com/codebude/QRCoder/wiki about the new classes @eulercamposbarros , @Ruffio , @sbrickey .

**Pull request merged**
