### PR TITLE
Add contact/phone number to WhatsApp Payload

### PR DESCRIPTION
**Pull request by taqabubaker**
This PR gives creates a new overload to the WhatsApp payload by giving the user the ability to add contact/phone number to WhatsApp Payload. This is can be achieved since WhatsApp is allowing passing the contact/phone number in the following format
`$"whatsapp://send/?phone={number}&text={message}"`

This PR fixes/implements the following **features**:

* [X] Add contact/phonenumber to WhatsApp Payload

What existing problem does the pull request solve?
Just adding gives the user a new feature to send the WhatsApp message directly to the desired contact.

**Test plan**

Demonstrate that your code is solid. If possible add a short test case/test steps.
UnitTests:

- [ whatsapp_generator_can_generate_payload_simple] still working.

- [ whatsapp_should_add_unused_params] new unit test method to test if the phone number is missing. 

**Closing issues**

Fixes #

### CODE REVIEW

**Comment by codebude** [comment]
Thanks for your work! :+1:

**Comment by taqabubaker** [comment]
@codebude 
I believe we need to change the wiki page [https://github.com/codebude/QRCoder/wiki/Advanced-usage---Payload-generators#319-whatsappmessage](url)

Following should be changed. What do you think ?

> Good to know
Unfortunately it is impossible to handover a contact/phonenumber, because WhatsApp only accepts its internal contact ids, which can't be known at time of QR code creation.

**Comment by codebude** [comment]
@taqabubaker You're right. In addition the table with the overloads has to be expanded. Or should I say had... Have a look at the wiki - I already updated the article. ;-)

**Comment by taqabubaker** [comment]
@codebude don't forget to publish a new version of the nuget package. :wink:

**Comment by codebude** [comment]
@taqabubaker I will push a new version during the next week. I like to check the other issues in front of. Maybe I can fix one or more things. (I don't want to push multiple packages in a week, but prefer to put as much as possible into the releases.)

**Pull request merged**
